name: SLinC CI
on:
  pull_request:
  push:
    branches:
      - "master"


jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1.3.0
        with:
          jvm: temurin:1.17
      - run: sbt scalafmtCheck scalafmtSbtCheck

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - run: mkdir reports
      - name: Core tests
        run: sbt coverage test

      - run: |
          sbt coverageReport
          mkdir -p reports
          cp target/scala-3.3.1/scoverage-report/scoverage.xml reports/scoverage.xml
      # - run: |
      #     ./mill core.scoverage.xmlReport
      #     cp out/core/scoverage/xmlReport.dest/scoverage.xml reports/core-coverage.xml
      #   env:
      #     JAVA_HOME: ${{ env.JAVA_HOME_17_X64}}



      # - name: Java 17 Implementation test
      #   run: |
      #     ./mill j17.compile
      #     ./mill j17.test
      #   env:
      #     JAVA_HOME: ${{ env.JAVA_HOME_17_X64}}

      # - run: |
      #     ./mill j17.scoverage.xmlReport
      #     cp out/j17/scoverage/xmlReport.dest/scoverage.xml reports/java17-coverage.xml 

      #   env:
      #     JAVA_HOME: ${{ env.JAVA_HOME_17_X64}}

      # - name: Java 19 Implementation test
      #   run: |
      #     ./mill j19.compile
      #     ./mill j19.test

      # - run: |
      #     ./mill j19.scoverage.xmlReport
      #     cp out/j19/scoverage/xmlReport.dest/scoverage.xml reports/java19-coverage.xml

      # - name: Runtime 17 implementation tests
      #   run: ./mill runtime.test
      #   env:
      #     JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

      # - run: |
      #     ./mill runtime.scoverage.xmlReport
      #     cp out/runtime/scoverage/xmlReport.dest/scoverage.xml reports/java-17-runtime-coverage.xml

      #   env:
      #     JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

      # - name: Runtime 19 implementation tests
      #   run: ./mill runtime.test
      # - run: |
      #     ./mill runtime.scoverage.xmlReport
      #     cp out/runtime/scoverage/xmlReport.dest/scoverage.xml reports/java-19-runtime-coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: reports
